### PR TITLE
add doc for rocker hot reloading

### PR DESCRIPTION
**Pull request by dz-1**

### CODE REVIEW

**Comment by stevehu** [comment]
Is there any way we can make the hot-reload as default?

**Comment by dz-1** [comment]
@stevehu 
Yes, we only need to set the `reload` variable to true in Cli.java.
The side effect is the command will fail if `rocker-compiler.conf` is not in the classpath.

**Comment by dz-1** [comment]
Or, we can modify the [shell script](https://github.com/networknt/light-codegen/blob/fix/issue_225/codegen-cli/codegen.sh) to pass in `-r` option by default.

**Comment by stevehu** [comment]
We don't know how many people are using the shell script. Most people are using the command line directly I think.

**Comment by dz-1** [comment]
ok. Then, they need to know how to setup the configurations and classpath.
The shell script can be used as a guide for them to setup their environment.

**Review by ddobrin — COMMENTED** [review]
Developers here at my client are using both Mac and Windows and are using it at this time from the command line.

Would then shell and cmd scripts be provided to them? And kept in sync?

**Comment by dz-1** [comment]
The script can be run in git bash on Windows.

**Comment by ddobrin** [comment]
I know that, and I have no problem with that, as I am using only GitBash, however it was a request from the client.

You can document it and explain it as such, as you please

**Comment by dz-1** [comment]
Ok, I'll create a bat version of the script since it's a client request.

**Comment by dz-1** [comment]
@ddobrin My Windows laptop cannot run any `bat` script. The best I can do is to provide a powershell script.

**Comment by ddobrin** [comment]
ok, that would address their requirements and in the meantime recommendations can be made to use shell scripts.

**Comment by dz-1** [comment]
@ddobrin 
The [Powershell script](https://github.com/networknt/light-codegen/commit/e783d2007c2c619baff60e78b65ad85d5b728e3f) has been added.

**Review by ddobrin — APPROVED** [review]

**Review by stevehu — APPROVED** [review]

**Pull request merged**
