### PR TITLE
Feature/#385 status merge

### PR DESCRIPTION
**Pull request by jiachen1120**
An alternate solution is added to the RFC.

### CODE REVIEW

**Review by ddobrin — APPROVED** [review]
@jiachen1120 : Just to be on the safe side:

let's use `application-status.yml` across the board in the doc, as application.yml is something services can set themselves today, with the name of the service

**Comment by stevehu** [comment]
Had a discussion with @BalloonWen this afternoon about the same topic and we are using app-status.yml on the whiteboard to make it shorter. Should we use app-status or application-status?

**Comment by BalloonWen** [comment]
Maybe shorter is better?  I prefer app-status.

**Review by BalloonWen — APPROVED** [review]

**Comment by ddobrin** [comment]
In the end it is immaterial, however think always what a developer thinks at first sight, as this is the audience

**Comment by stevehu** [comment]
Let's use app-status.yml if there is no objection then.

**Review by ddobrin — CHANGES_REQUESTED** [review]
The document has changed after an approval has been provided:

**[2]** If the status code in application-status.yml is contained by status.yml, an Exception should be thrown since the status code in status.yml is used by framework itself, they should be immutable. 

This is the correct behaviour.

**Comment by ddobrin** [comment]
@BalloonWen : could you please send a different PR for the file: Create 0016-Router-Client-Accepting-Provided-Scopes-for-Auth.md?

I think it is unrelated to 0015

**Comment by BalloonWen** [comment]
@ddobrin sorry, my mistake, wrong branch, I'll create my own.

**Review by stevehu — APPROVED** [review]

**Review by ddobrin — APPROVED** [review]

**Pull request merged**
