### PR TITLE
Create 0011-set-type-for-value-injection.md

### PR DESCRIPTION
**Pull request by jiachen1120**
This RFC is related to the first point of the issue: https://github.com/networknt/light-4j/issues/371

There are three way mentioned in the RFC and look forward to your opinions.

### CODE REVIEW

**Review by ddobrin — COMMENTED** [review]
@jiachen1120 I do agree with you that enabled: "true" is not something which developers would be doing, or not naturally.

One opinion and some asks (or recommendations for the light-codegen).

In my **opinion**, and if you wish to go for an exhaustive approach and minimize potential errors I would summarize your proposal as:

1. recommend the usage of environment variables with an addition of the type, as in: 
`${key#type:default_value}`

2. Developer is not mandated to specify the type, yet it is recommended

3. Developer is not mandated to use "true" for boolean, for example

4. if the developer doesn't specify the type, as in : `${key:default_value}`, the behavior should be similar to how YAML files would be treated, with a consistent return for `${key:true} and key:true `and a different return for `key:"true" vs key:true`, as in String vs boolean

5. Lists and Maps remain outside of this effort

Did I get it right? I think that this should be meeting all needs.

Now, the asks (or recommendation):
1. light-codegen will generate environment variables on demand, configuration-based. If it is decided to include the type, can we mandate that codegen sets the types as well?
2. there is a separate issue, completed and closed at this time, which generates a default values.yml file with a number of commonly used parameters. If it is decided that we use the type, then can the values.yml fiel also be updated to reflect this?

**Comment by jiachen1120** [comment]
Hi @ddobrin , after discussion with @NicholasAzar, I think that adding "type" may be too cumbersome and even lead to new problems, perhaps we can directly follow the snakeYaml's solution. That is, any string will be tried to be cast. all integers are converted to int, all decimals are converted to double, and all true and false are converted to Boolean values. In this way, we do not need to change anything in codegen and config files. Just some simple methods added to cast type. I will write an RFC to specify the details.

**Review by stevehu — APPROVED** [review]
I like the idea to use user-friendly snakeyaml approach.

**Comment by ddobrin** [comment]
Thats should also work and be simpler

**Review by ddobrin — APPROVED** [review]

**Review by DSchrupert — APPROVED** [review]

**Pull request merged**
