### PR TITLE
Fix/error message when registration failure

### PR DESCRIPTION
**Pull request by jiachen1120**
This RFC is related to API-7 

Currently, when a configuration issue or some other problem results in the service failing to register in consul, the log message outputted to the user is that the service failed to bind to whatever port. This causes confusion. In this RFC, a solving method is suggested. 

However, even though the user can get the correct exception information. There are still problems that need to be resolved. That is, when the registration fails, the server is still running. 
So should we stop the server at this moment and output the "server stops due to registration failure."? Look forward to your suggestion and opinion. @stevehu @NicholasAzar @ddobrin

### CODE REVIEW

**Comment by jiachen1120** [comment]
@stevehu Thanks for the reply.
Yes, I think it is reasonable to let the server stop and let the user solve the problem of not being able to register if the configuration error is the only reason for the registration failure. However, is it possible that the registration failed due to some other reasons, and if you try to register again, it will still succeed? In other words, is there any other situation that would cause an accidental registration failure and should probably be retried automatically at the moment? 

In addition, do you mean that when we catch some exceptions we throw the runtime exception in the catch block? or stop the server by using server.stop() and output the correct information in the console?

**Comment by stevehu** [comment]
There are two reasons that I can think of: 

* The connection info is not correct in the config files. For example, the URL is wrong, the consul token is missing or wrong. 

* The client.truststore doesn't have the certificate to connect to the consul server. 

In both situations, we should stop the server. 

I haven't looked into the code yet, but at least one way to stop the server is to throw a runtime exception and there are several places we are using that already.

**Comment by jiachen1120** [comment]
@stevehu @NicholasAzar @ddobrin  Hi, I just make some changes in the RFC and The branch related to this issue can be checked here https://github.com/networknt/light-4j/tree/fix/error-message-when-fail-registration. Look forward to your opinions!

**Comment by stevehu** [comment]
@jiachen1120 You can just use RuntimeException with a message in the constructor without creating another RegistrationException. As it is a RuntimeException, you don't need to catch it in the outer try block and it will bubble up until sever is stopped. I am not 100 percent sure but give it a try. Thanks.

**Comment by jiachen1120** [comment]
@stevehu Yes, I have tried to do this, but the runtime exception will still be caught by the outer try-catch here, which used to report the bind error message.
```
} catch (Exception e) {
            System.out.println("Failed to bind to port " + port);
            if (logger.isInfoEnabled())
                logger.info("Failed to bind to port " + port);
            return false;
        }
```
and cause the wrong information. Without changing the current structure, we may need an additional exception such as registration exception. But I also think it is not worth to create a new exception just for that. So, maybe we can just change the structure by catching the bind error earlier after the server.start and before the register? Thanks

**Review by stevehu — APPROVED** [review]

**Review by DSchrupert — APPROVED** [review]
Looks good, I agree that the server should not come up if the service fails to register. One thing to potentially keep in mind is that Kubernetes will try to restart the service with an exponential fall back. So the error message should be descriptive that it's not the service that's at fault, but rather the registry service.

**Pull request merged**
