### PR TITLE
Add logging module for light 4j

### PR DESCRIPTION
**Pull request by sreeni1990**
New logging module created for light 4j to see and change the logging levels .

### CODE REVIEW

**Review by DSchrupert — APPROVED** [review]

**Comment by DSchrupert** [comment]
We do need to consider what type of security feature we can add to this later

**Comment by stevehu** [comment]
Since these are API endpoints and it makes sense to have OAuth 2.0 scopes to protect them.

**Comment by DSchrupert** [comment]
I'm not sure we want to have all our operations individuals to create an oauth client and have to fetch tokens.. will have to reach out to see what would fit into their workflow

**Comment by stevehu** [comment]
My assumption is that these endpoints will be accessed by an automation pipeline like light-bot and getting a token with a user's credential is very crucial. When this is running from the operator's desktop, the OAuth 2.0 provider should integrate with Kerberos/SPNEGO to get the credentials from desktop and get a token with user id for accessing the logging endpoint. If it is running on a jump box, he/she should input the username/password to get the token. 

Other options like 2-way TLS and Basic Authentication is not secure as there is no user's credential available for auditing.

**Review by santoshaherkar — APPROVED** [review]

**Pull request merged**
