### PR TITLE
Create 0005-fix-uncompilable-generation-caused-by-naming.md

### PR DESCRIPTION
**Pull request by jiachen1120**
In some scenarios invalid java is generated from the codegen such that the services fail to build. The details and solutions are included in this RFC.

Related issue: https://github.com/networknt/light-codegen/issues/236

Look forward to your reviews!

### CODE REVIEW

**Comment by stevehu** [comment]
Most of these kinds of issues are related to the specification pre-processing. We need to transform the model which is the spec before feeding to the template for code generation. @jsu216 @miklish and I had a chat about the pre-processor and post-processor that can be injected into the codegen with service.yml or externalized values.yml file. I think that might be the right route to inject logic to prepare the model. @jsu216 has implemented something already so please have a chat with him and see if we can leverage his code.

**Comment by jiachen1120** [comment]
@stevehu Thanks, I will discuss with @jsu216 then

**Comment by ddobrin** [comment]
The challenge here will be maintaining the same output for the generated files as today, as some clients already have a significant number of specifications defined and have built microservices using the generated model classes

**Comment by jiachen1120** [comment]
@ddobrin Yes, the output structure will keep same after this fixing. Just to solve some corner cases to prevent uncompilable java code appearing.

**Review by DSchrupert — APPROVED** [review]

**Pull request merged**
