### PR TITLE
code-generation-with-env-values-support

### PR DESCRIPTION
**Pull request by ddobrin**

### CODE REVIEW

**Review by GavinChenYan — APPROVED** [review]

**Review by stevehu — APPROVED** [review]
@ddobrin I like the idea to put the list of handlers into the config.json for users to customize their handler chain with a default list if the customized list is not specified and associate the handlers with their corresponding configurations files. This resolves the disconnect between the handler injection and handler configuration injection. 

To use a flag in config.json to specify if the user wants to use environment variables or values.yml and generate config files with default values or with environment variable templates definitely better than the current fix for #208 (https://github.com/networknt/light-codegen/pull/213) which @NicholasAzar is concerned.

**Review by DSchrupert — APPROVED** [review]
Looks like this is two distinct features, which I'm good with both as I mention below, but would like to see them separated into their own RFCs in the future. They are unrelated as far as I'm aware.

1. For generating the specific handler's config based on a list of provided handlers, I think this is a good feature to have. It will allow teams to include either more or less config as they see fit. 👍 
2. Having a flag indicate whether config fields get generated with environment variable injection enabled or disabled addresses the concern I raised in the past change, and I'm fine with including. To emphasize, this should be disabled by default.

**Comment by stevehu** [comment]
@ddobrin could you please create 2 separate issues in light-codegen? Thanks.

**Comment by ddobrin** [comment]
Issues have been created the other day

**Comment by stevehu** [comment]
References to the issues:
https://github.com/networknt/light-codegen/issues/216
https://github.com/networknt/light-codegen/issues/217

**Pull request merged**
