### PR TITLE
Create 0024-Support-Direct-ServiceURL-Lookup-and-Consul-Service-Disco…

### PR DESCRIPTION
**Pull request by jsu216**
…very at same time.md

### CODE REVIEW

**Comment by jsu216** [comment]
This PR is for the issue:  https://github.com/networknt/light-4j/issues/611

**Comment by stevehu** [comment]
@jsu216 The direct registry is designed for local test only before the users can set up official test environment with Consul or Zookeeper. It doesn't have the necessary cluster, load balance, environment segregation support for any official testing and production usage. Could you please explain your use cases? Thanks.

**Comment by jsu216** [comment]
There actually are some use cases that use DirectRegistry in official deployment to control the service discovery results. E.g. In certain situations, we cannot register services in Consul but we still want the client to call them with service_id instead of exposing the URIs.
Moreover, the services that clients want to access cannot all be registered in Consul and we need to allow them to be accessed through the same router instance. This is where this requirement came from.

**Comment by stevehu** [comment]
I assume these services are legacy services or built with other languages. In most of the cases, they are lack of other features to be integrated into the light-4j ecosystem. The solution is to put a light-proxy instance in front of the service to handle the security, logging, tracing, metrics, etc. The direct registry is far from any realistic usage in my opinion and it needs a full redesign to be comparable with Consul registry.

**Comment by miklish** [comment]
What additional items do you suggest are needed to the direct registry? Legacy services are almost always accessed via static DNS, and are already behind a load balancer, so much of the functionality of the Consul registry (e.g.: client side load balancing) is unneccessary when connecting to them.

**Comment by stevehu** [comment]
The registry is for discovery dynamic services in the cloud as they don't have static IPs and port numbers. In case you Legacy service is accessible via static DNS with a load balancer, you don't need discovery at all. Just call the service directly. The end result of the discovery is the host IP and port number which is known for your static service. 

The direct registry was built as a place holder for Consul registry or Zookeeper registry so that users can use it in service.yml in the beginning and later switch to Consul or Zookeeper in the official test environment without modifying the code. It is never considered to be usable or useful. 

If you follow the service discovery tutorial, we are creating a service-specific config file for static service in the first step. https://doc.networknt.com/tutorial/common/discovery/static/ and I think it might be a better option for your static service. 

BTW, the solution I recommend in the previous post with light-router or light-proxy has its merit. Even your static service is behind a load balancer, it might need other gateway cross-cutting concerns to be handled like security, metrics, tracing and auditing, rate limiting, etc. To put a gateway in front of it will bring your legacy service into the light ecosystem and for all other services/clients, your legacy service is just like another light-4j service. Putting a distributed gateway for a legacy service is the most popular solution in the industry nowadays and service mesh is even putting gateways for services in the same cluster. The idea is for smooth integration without touching the existing service to resolve gateway concerns.

**Comment by jsu216** [comment]
Cancel this PR as a result of the discussion above.

**Pull request closed without merging**
