### PR TITLE
0019-pluggable-config-server-feature.md

### PR DESCRIPTION
**Pull request by santoshaherkar**
PR for actual implementation is coming soon

### CODE REVIEW

**Comment by stevehu** [comment]
@santoshaherkar, welcome to the team. The light platform is designed to be extended with plugins and it would be fantastic to have pluggable config servers. 

One thing that we need to consider for the config server interaction is security. The connection between the service and the config server should be HTTPS. To establish HTTPS connect, the service instance needs client.yml to load the truststore which means certain config files are not supposed to load from the config server. This is the implementation detail but I think it would be better to document it in the RFC so that others can understand how this supposed to be working. Thanks.

**Comment by DSchrupert** [comment]
@stevehu 
I dont think this rfc is for the specific implementation details for what is required to enable config server integration, but rather just a way to externalize whatever implmentation details are required to a startup hook so that different teams have flexibility.

@santoshaherkar 
This solution still requires service.yml before it can get other config from the server.. is there a way around this? Maybe putting the class reference in a config-server.yml?

**Comment by santoshaherkar** [comment]
You are right @NicholasAzar ; I can add the class reference to startup.yaml or to some other yml file but then we will have to change the framework to read this new file and then mimic the SingletonServiceFactory (which reads service.yml by default) logic there to create instance of the class.

**Comment by santoshaherkar** [comment]
@NicholasAzar I have changed this RFC & Code PR from StartupHookProvider to ConfigLoader approach to support config injections in service.yml configs as well.

**Review by DSchrupert — APPROVED** [review]

**Comment by stevehu** [comment]
@santoshaherkar I see that a new startup.yml is introduced in the solution. I am wondering if it is possible to put it into the server.yml or config.yml as an additional section. So far, all configuration files are matched to the modules in light-4j except values.yml which is centralized dynamic variables for all modules. I haven't looked at the implementation yet and don't know if you are going to introduce a new module in light-4j. If yes, we can use the module name as config file name.

**Comment by santoshaherkar** [comment]
@stevehu we don't have separate startup module as such but this startup.yml file contains minimum static configurations required to call the config server and fetch the configs. It does not have any parameterized values that needs to be replaced at run time. (We can not inject the values while calling config server as we don't have them yet).  
Other config files may have parameterized values to be replaced at run time & if we put these configs there, we wont be able to inject other values.

**Comment by stevehu** [comment]
@santoshaherkar I have reviewed your code and it makes sense now. Since this a very special case, let's use startup.yml for the config file name. We just need to clearly document it so users know when and how to use the startup.yml file. My understanding is that it is only to be used when you want to plug in another config server implementation. Please correct me if I am wrong. Thanks.

**Review by stevehu — APPROVED** [review]

**Comment by santoshaherkar** [comment]
@stevehu Currently startup.yml is required if you want to use any config loader including existing one. But I can change it to default to existing default config loader in case startup.yml is not provided or if its missing the config loader class.

**Comment by santoshaherkar** [comment]
@stevehu I have changed the code to default to DefaultConfigLoader. So now startup.yml is required only if you want to use your own implementation.

**Comment by stevehu** [comment]
@santoshaherkar Thanks a lot for the update. The default behavior helps a lot of existing users to upgrade to the latest version.

**Pull request merged**
