### PR TITLE
Create 0020-oauth-enhancement.md

### PR DESCRIPTION
**Pull request by jiachen1120**
related issue: https://github.com/networknt/light-4j/issues/472

### CODE REVIEW

**Comment by DSchrupert** [comment]
Will this be driven by config? What are the changes required to `client.yml`?
Also how will this be integrated in client module usage? Like will the existing .addCcToken() also include the custom claims if those are specified in the client.yml? Will there need to be updates to the consumer module to support this as well?

**Comment by stevehu** [comment]
@jiachen1120 Could you please provide the business case that drives the enhancements?

**Comment by DSchrupert** [comment]
@stevehu the high level purpose is we no longer want service specific data/config stored and maintained in the auth server, but rather have the clients explicitly request whatever custom claim information they want within their request. In this way i believe we limit exposure to clients by not always sending them information they might not need in their token, and allow a more fluid mechanism to update that information at the whim of the client instead of depending on a client profile change in the auth server.

**Comment by jiachen1120** [comment]
@NicholasAzar @stevehu  Hey. It is not driven by config and no requirement to change the client.yml. The aim for this enhancement is to provide user an overload method to control the caching and support more tokenRequest way.

Before the change, Jwt cache only depends on the scope and cannot be customized. And the request only have two types (client credential and saml). However, some organization hope they can cache the jwt by using custom claims or other things. And In our project (light-spa-4j), we can cache the Jwt by using refreshToken. Therefore. To provide a method people can parse in their customized cache key would be helpful.

In terms of token request, similar to cache key, it should also be more flexible to customize. For example, people can choose whether using client secret in token request.

There is no new usage just extension, provide same reload methods in TokenManager.

Before, when people want to get Jwt, they invoke:
TokenManager.getInstance.getJwt(Jwt); (In light-router)

Now, this enhancement provide user the method:
TokenManager.getInstance.getJwt(Jwt.key key, TokenRequest tokenRequest);

People can customized the key, for example:
using `key.setScopes(scope)` means the scope will be the key to cache Jwt;

**Comment by stevehu** [comment]
My understanding is that the custom claims are used for fine-grained authorization in the business context just like the scopes are for technical authorization to control at the endpoint level of service. Are you defining the entire list of custom claims on the OAuth2 provider and use them to verify the custom claims sent from the clients like how the scopes work?

**Comment by DSchrupert** [comment]
@stevehu from my understanding it would be the same as scopes from the client perspective (they would have to send in whatever custom claims they want in their token), however the auth server won't maintain an "approved" type list the same way that it does for scopes. It will accept any value that the clients wish to include in the token.

**Review by ddobrin — CHANGES_REQUESTED** [review]
The consumer (using the Client module) is agnostic in the code at this time of scopes, custom claims or other token related information.

The client.yml allows you to specify scopes and developers can not provide incorrect code, as the information is automatically handled by the Client module when creating the TokenRequest.
DevOps team control which values are set in the client.yml file.

The same approach should apply to the custom claims.

If the direction at some clients is to offload the registration of custom claims from the authorization server to the client, it should not preclude other implementations to impose a tighter control and not implement the functionality.

Setting it as a:
  authorization_code:
      # token endpoint for authorization code grant
      uri:...
      # client_id for authorization code grant flow. client_secret is in secret.yml
      client_id: ...
      # the web server uri that will receive the redirected authorization code
      redirect_uri: ...
      # optional scope, default scope in the client registration will be used if not defined.
      scope:a.r b.w
      custom: a:b c:d

would address it better, and provide better control, one which can be controlled via config server for example

**Comment by jiachen1120** [comment]
@ddobrin Hey, I just updated the code to let the client module to support custom claims in request header and work the same way as scope does. 

The previous enhancement is aim to provided a flexible compose way for get token from oath server. Some organization would have their own auth server but variable standard. The client module will not use this overload method, but another project required these method to flexibly get Jwt based on the their own auth server structure.

The only different for client module is user can put custom claims in their request header as a part of parameters required by auth server to get Jwt. And no other changes is needed for user. The overload methods would not influence the client module and would just used for the third party who have different auth standard.

**Comment by DSchrupert** [comment]
Hi @jiachen1120 as discussed this should be supported by the client module through interface along with scopes for consumers to be able to pass the value explicitly, or have it default to the client.yml file content

**Pull request closed without merging**
