### PR TITLE
Acme integration

### PR DESCRIPTION
**Pull request by shabeebrp**

### CODE REVIEW

**Comment by stevehu** [comment]
1. For localhost and development, we can still provide the self-signed certificate as part of the light-codegen so that users can start with HTTP/S immediately without worrying about how to set it up. 

2. I am not aware of the 50 limitations for subdomains as I never use more than 10 subdomains per domain so far. If a company like heroku wants to provide hosting service, they should have their own CA to issue certificates. We can aim to the users who own at least one domain for now until we reach the point that we can to provide hosting services for APIs. 

3. I think we need to handle two scenarios: (a) If the user service is public, then the service should support the ACME directly when the service is exposed to the Internet directly. Sometimes, we cannot expect the service to be exposed to the Internet directly but might be behind a DNS service like Cloudflare. In this case, we cannot make the retrieval/renewal or automatic and it might be an endpoint the is part of the service. (b) If the service is an internal one with a subdomain name not exposed to the Internet, we might need to provide a service that can be deployed to the cloud or DMZ to be responsible for getting the certificate only.

4. In both scenarios, we need to get the private key, the certificate, and the full chain from ACME API and create server.keystore, server.truststore, client.keystore, and client.truststore. These files can be later on copied to the right service through the pipeline. 

5. If fully integration is hard to do, then we can aim to build a service to generate the files specified in step 4 first. It might cover the majority of the use cases.

**Comment by shabeebrp** [comment]
@stevehu totally agree with the 5th point. If we have a module which will do the most of the work related to acme like registration, renewal, expiration, etc, other modules like the server can use this to get certificates.
We can also give users the option of whether they want to use acme or not.
In fact there is a web server called caddy which is written in go lang, and their main USP is automatic HTTPS [caddy](https://caddyserver.com/).

**Comment by stevehu** [comment]
caddy looks really nice. There are a lot of creative open source projects we can learn from on the GitHub.com

**Review by jefperito — APPROVED** [review]
i agree with this rfc, i just have a suggestion, not create a coupling between server and acme modules.

**Comment by shabeebrp** [comment]
@jefperito I was also thinking the same. acme module should be concerned about getting a new certificate or renewing a certificate. Storing these certificate in sever.keystore or anywhere else should be the concern of the module which is using the acme module. In our case server can request acme module for the certificate or renew an existing certificate. Once the acme module has the certificate, it can pass it to the server module. Then the server module can store the certificate where ever it wants( server.keystore).

**Comment by stevehu** [comment]
Totally agreed. The smaller the module, the better.

**Review by stevehu — APPROVED** [review]

**Pull request merged**
